version: "3.8"
networks:
  intergration-test:
    driver: bridge

services:
  db:
    image: mdillon/postgis:11
    container_name: postgres
    restart: on-failure
    healthcheck:
      test: /usr/bin/pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 120
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
    - pg_data:${PGDATA:-/var/lib/postgresql/data}:rw
    - ./docker/01-init-user.sh:/docker-entrypoint-initdb.d/01-init-user.sh
    ports:
      - 5432
    networks:
      - intergration-test

  mapstore:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OVR: "geostore-datasource-ovr.properties"
        MAPSTORE_WEBAPP_SRC: "https://github.com/geosolutions-it/MapStore2/releases/latest/download/mapstore.war"
        PG_CLIENT_VERSION: 11
    container_name: mapstore
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080
    networks:
      - intergration-test

volumes:
  pg_data:

